name: Incident Automation

on:
  workflow_dispatch:

jobs:
  incident-health-check:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Run Automation
        run: |
          chmod +x incident_automation.sh
          ./incident_automation.sh
